syntax = "proto3";
package com.staploy;

import "protocol.proto";
import "app.proto";

enum TaskGroup {
  TASK_NONE = 0;
  TASK_MANAGE_APPS = 1;
  TASK_MANAGE_NODE = 2;
  TASK_DEPLOY = 3;
}

enum TaskAppsTypes {
  TYPE_APP_NONE = 0;
  TYPE_APP_REGISTER = 1;
  TYPE_APP_DELETE = 2;
  TYPE_APP_LISTS = 3;
  TYPE_APP_PKG_PARSE = 4;
  TYPE_APP_PKG_CREATE = 5;
}

enum TaskNodeTypes {
  TYPE_NODE_NONE = 0;
  TYPE_NODE_CONNECTED = 1;
  TYPE_NODE_EXECUTE_SHELL = 2;
  TYPE_NODE_REQ_WORKER_INFO = 3;
  TYPE_NODE_REQ_APP_INFO = 4;
  TYPE_NODE_DISCONN_WORKER = 5;
}

enum TaskDeployTypes {
  TYPE_DEPLOY_NONE = 0;
  TYPE_DEPLOY_PUSH_VERSION = 1;
  TYPE_DEPLOY_SET_VERSION = 2;
  TYPE_DEPLOY_DEL_VERSION = 3;
}

message ResponsePacket {
  string status = 1;
  string error_cause = 2;

  optional string extra_data = 3;
  repeated WorkerPacket workerResponse = 4;
}

message RequestPacket {
  TaskGroup task_group = 1;
  optional string extra_data = 2;
  repeated WorkerInfo worker = 3;
  repeated AppInfoFetch appInfoFetch = 4;

  oneof taskType {
    TaskAppsTypes appsTaskType = 10;
    TaskNodeTypes nodeTaskType = 11;
    TaskDeployTypes deployTaskType = 12;
  }
}

message PackageHeader {
  int64 formatVersion = 1;
  bool shareOnly = 2;

  InstalledAppInfo packageInfo = 10;
}