syntax = "proto3";
package com.staploy;
import "protocol.proto";

enum TaskGroup {
  TASK_NONE = 0;
  TASK_MANAGE_APPS = 1;
  TASK_MANAGE_NODE = 2;
  TASK_DEPLOY = 3;
}

enum TaskAppsTypes {
  TYPE_APP_NONE = 0;
  TYPE_APP_REGISTER = 1;
  TYPE_APP_DELETE = 2;
  TYPE_APP_LISTS = 3;
  TYPE_APP_BLOB = 4;
}

enum TaskNodeTypes {
  TYPE_NODE_NONE = 0;
}

enum TaskDeployTypes {
  TYPE_DEPLOY_NONE = 0;
}

message ResponsePacket {
  string status = 1;
  string error_cause = 2;
  string challengeCode = 3;
  optional string extra_data = 4;
}

message RequestPacket {
  TaskGroup task_group = 1;
  optional string challengeCode = 2;
  optional ProtocolProcedure protocol_procedure = 3;
  optional string extra_data = 4;
}